### ISSUE TITLE
Missing data `fridge_:0000_rearrange.json.gz`

### ISSUE THREAD

**Issue by hatimwen** [absdnd/aux_distill#3]
In the config file of training `open_fridge_pick`, it sets a data path:

https://github.com/absdnd/aux_distill/blob/17f7049312af57b2d02f91069d22b5451ccc3413/skill_chain/configs/aux_distill/env_tasks/skills/open_fridge_pick/config.yaml#L10

Does this path point to the `open_fridge_pick.json.gz` file you shared on [Google Drive](https://drive.google.com/drive/folders/1TBaCxWnNP8xYoluNl1Yrh7zWYS3CkJkA?usp=sharing)?

**Comment by absdnd** [comment]
Yes, that is correct.
